# Generated by Django 2.2 on 2019-04-13 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0020_event_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, help_text='This will be used to generate the URL of the page. Please only use latin letters, numbers, dots and dashes. You cannot change this afterwards.', max_length=150, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9.-]+$')], verbose_name='URL to static page')),
                ('position', models.IntegerField(default=0)),
                ('title', i18nfield.fields.I18nCharField(verbose_name='Page title')),
                ('text', i18nfield.fields.I18nTextField(verbose_name='Page content')),
                ('link_on_frontpage', models.BooleanField(default=False, verbose_name='Show link on the event start page')),
                ('link_in_footer', models.BooleanField(default=False, verbose_name='Show link in the event footer')),
                ('require_confirmation', models.BooleanField(default=False, verbose_name='Require the user to acknowledge this page before the user action (e.g. for code of conduct).')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
    ]
